# Generated by Django 2.2.11 on 2020-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10, verbose_name='Gender')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('info', models.CharField(help_text='Introduce yourself in 250 words or less', max_length=255, verbose_name='Student Introduction')),
                ('grade', models.CharField(max_length=4, verbose_name='Grade')),
                ('number', models.CharField(max_length=6, verbose_name='Number')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10, verbose_name='Gender')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('info', models.CharField(help_text='Introduce yourself in 250 words or less', max_length=255, verbose_name='Faculty Introduction')),
                ('department_no', models.CharField(max_length=3, verbose_name='Department Number')),
                ('number', models.CharField(max_length=7, verbose_name='Number')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('department_no', 'number'), name='teacher_id'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('grade', 'number'), name='student_id'),
        ),
    ]
